server:
  port: 8888

spring:
  application:
    name: service-zuul


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8881/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}
zuul:
  routes:
    api-a:
      path: /hello/**
      serviceId: service-hello
    api-b:
      path: /feign/**
      serviceId: service-feign


